version: "1.0"
info:
  model: int-scaffold
packages:
- name: May09LDSProject
  gitServerName: shshi
  gitUrl: https://github.com/Shilpa-Shivaji-IBM
  gitUsername: Shilpa-Shivaji-IBM
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: WmSAP
  version: 10.1.0.0.1013
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_1
  packages:
  - name: May09LDSProject
    version: "1.0"
  - name: WmSAP
    version: 10.1.0.0.1013
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections:sdfd
  packages:
  - name: May09LDSProject
    version: "1.0"
  - name: WmSAP
    version: 10.1.0.0.1013
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.may09lds.integrations:shshi
  packages:
  - name: May09LDSProject
    version: "1.0"
  - name: WmSAP
    version: 10.1.0.0.1013
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.may09lds.integrations:tesrtf
  packages:
  - name: May09LDSProject
    version: "1.0"
  - name: WmSAP
    version: 10.1.0.0.1013
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: project.may09lds.integrations:tfghh
  packages:
  - name: May09LDSProject
    version: "1.0"
  - name: WmSAP
    version: 10.1.0.0.1013
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: pub.datetime:build
  packages:
  - name: WmPublic
    version: 11.1.0.0.2050
configurationVariables:
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.oracle.OracleDataSource
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.sncQualityOfService
  : Use global build-in default settings
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.abapDebug
  : "Off"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.password
  : "{AES}R4jeBvwt1uq6OWI+clea/g=="
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.loadBalancing
  : "Off"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.logonGroup
  : ""
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.language: ""
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.user: sddd
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.poolable
  : "false"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.testConnection
  : "Off"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.trustStore
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.serverName
  : dfd
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.repoUser: dfd
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.repositoryServer
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.appServerHost
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.routerString
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.user
  : dff
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.storeMsgBody
  : "On"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.blockingTimeout
  : "1000"
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.sapGui: "Off"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.programId
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.sncPartnerName
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.dbType
  : ORACLE
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.otherProperties
  : loginTimeout=60;
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.sncMode: "No"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.sncAuthentication
  : User and Password
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.client: "444"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.connectionType
  : "No"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionManagerSettings.poolable
  : "false"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.portNumber
  : "1521"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.messageServerHost
  : ""
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionEnabled: "false"
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.rfcTrace: "Off"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.transactionType
  : NO_TRANSACTION
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.password: "{AES}06xLLfhhTsrp5PvO5fwHYg=="
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.repoPassword
  : '******'
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.networkProtocol
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.messageServerService
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.systemNumber
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.heartBeatInterval
  : "0"
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.systemId: ""
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionEnabled
  : "false"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.logTransactionStatus
  : "On"
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.databaseName
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.gatewayHost
  : ""
  artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.alias: sdfd
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.sncMyName
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_1.connectionSettings.keyStore
  : ""
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.May09LDSProject.project.may09lds.WmSAP.com_wm_adapter_sap_SAPAdapter.connections.sdfd.connectionSettings.gatewayService
  : ""
